name: Build and Deploy

on:
  workflow_call:
    inputs:
      env_input:
        type: string
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_input }}
    env:
      CI: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache (node)
        uses: actions/cache@v3
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --immutable --prefer-offline

      - name: Build node
        run: npm run build

      - name: Cache (firebase)
        uses: actions/cache@v3
        id: cache-firebase
        with:
          path: /usr/local/bin/firebase
          key: ${{ runner.os }}-firebase

      - name: Install firebase tools
        if: steps.cache-firebase.outputs.cache-hit != 'true'
        run: |
          curl -sL firebase.tools | bash

      - name: Deploy to Firebase
        run: |
          echo $GCP_SA_KEY > $GOOGLE_APPLICATION_CREDENTIALS
          firebase use $PROJECT_ID
          firebase deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp_sa.json
