name: Build and Deploy to Firebase
on:
  push:
    branches:
      - master
      - dev
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Npm install
        uses: bahmutov/npm-install@v1
      - name: Npm build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
